// utils/constants.js
const TRIP_STATUS = {
    ASSIGNED: 'ASSIGNED',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    EMERGENCY: 'EMERGENCY'
};

const TRIP_STOP_STATUS = {
    PENDING: 'PENDING',
    ARRIVED: 'ARRIVED',
    COMPLETED: 'COMPLETED',
    SKIPPED: 'SKIPPED'
};

const GOLD_COLLECTION_STATUS = {
    PENDING: 'PENDING',
    COLLECTED: 'COLLECTED',
    IN_TRANSIT: 'IN_TRANSIT',
    BANK_VERIFIED: 'BANK_VERIFIED',
    COMPLETED: 'COMPLETED',
    REJECTED: 'REJECTED'
};

const PHOTO_VERIFICATION_STATUS = {
    PENDING: 'PENDING',
    VERIFIED: 'VERIFIED',
    REJECTED: 'REJECTED'
};

const STOP_TYPE = {
    FRANCHISE: 'FRANCHISE',
    BANK: 'BANK'
};

const ALLOWED_STATUS_TRANSITIONS = {
    [TRIP_STATUS.ASSIGNED]: [TRIP_STATUS.IN_PROGRESS, TRIP_STATUS.CANCELLED],
    [TRIP_STATUS.IN_PROGRESS]: [TRIP_STATUS.COMPLETED, TRIP_STATUS.CANCELLED],
    [TRIP_STATUS.COMPLETED]: [],
    [TRIP_STATUS.CANCELLED]: []
};

const GEOFENCE_RADIUS_METERS = 100;
const LOCATION_UPDATE_INTERVAL = 30000; // 30 seconds

module.exports = {
    TRIP_STATUS,
    TRIP_STOP_STATUS,
    GOLD_COLLECTION_STATUS,
    PHOTO_VERIFICATION_STATUS,
    STOP_TYPE,
    ALLOWED_STATUS_TRANSITIONS,
    GEOFENCE_RADIUS_METERS,
    LOCATION_UPDATE_INTERVAL
};